Repository linq2db/linq2db, pull requests merged in 2018-05, with the labels that each got.

#1120 Working on failing tests
  NuGet/Readme.txt
  Source/LinqToDB/DataProvider/Firebird/FirebirdIdentifierQuoteMode.cs
  Source/LinqToDB/DataProvider/Firebird/FirebirdSqlBuilder.cs
  Source/LinqToDB/Linq/QueryRunner.Delete.cs
  Tests/Base/ScopedSettings.cs
  Tests/Base/TestBase.cs
  Tests/Base/TestUtils.cs
  Tests/Linq/DataProvider/FirebirdTests.cs
  Tests/Linq/Linq/ComplexTests2.cs
  Tests/Linq/Linq/DateTimeFunctionsTests.cs
  Tests/Linq/Linq/DynamicColumnsTests.cs
  Tests/Linq/Update/InsertTests.cs
  Tests/Linq/Update/UpdateTests.cs
  Tests/Linq/UserTests/Issue1057Tests.cs
  Tests/Linq/UserTests/Issue1110Tests.cs
Labels: provider-firebird

#1127 bugfix when inheritance is used #1128
  Source/LinqToDB/Extensions/MappingExtensions.cs
  Source/LinqToDB/Linq/QueryRunner.Delete.cs
  Source/LinqToDB/Linq/QueryRunner.Insert.cs
  Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs
  Source/LinqToDB/Linq/QueryRunner.InsertWithIdentity.cs
  Source/LinqToDB/Linq/QueryRunner.Update.cs
  Source/LinqToDB/Linq/QueryRunner.cs
  Source/LinqToDB/Mapping/EntityMappingBuilder.cs
  Source/LinqToDB/Mapping/FluentMappingBuilder.cs
  Source/LinqToDB/Metadata/FluentMetadataReader.cs
  Tests/Base/TestBase.cs
  Tests/Linq/Linq/ComplexTests2.cs
  Tests/Linq/Mapping/FluentMappingTests.cs
  Tests/Linq/UserTests/Issue1128Tests.cs
Labels: bug

#1136 bugfix sqlserver bulkkcopy with retry, fixes #1135
  Source/LinqToDB/DataProvider/SqlServer/SqlServerBulkCopy.cs
Labels: bug

#1153 Fix merge with empty source
  Source/LinqToDB/DataProvider/BasicMergeBuilder.cs
  Tests/Linq/Update/MergeTests.EmptySource.cs
  Tests/Linq/Update/MergeTests.Operations.Insert.cs
Labels: bug

#633 Added NVarchar2 DataType for oracle utf8 text data handling (when ins…
  Source/DataProvider/Oracle/OracleDataProvider.cs
  Source/DataType.cs
  Tests/Linq/DataProvider/OracleTests.cs
Labels: provider-oracle
