Repository linq2db/linq2db, pull requests merged in 2020-08, with the labels that each got.

#2396 Separate broken npgsql tstzrange tests for postgre
  Tests/Linq/DataProvider/PostgreSQLTests.cs
Labels: area: bulk-copy, area:tests

#2408 Add asynchronous overloads for CreateTempTable
  Source/LinqToDB/DataProvider/BasicBulkCopy.cs
  Source/LinqToDB/TempTable.cs
  Tests/Linq/Update/CreateTempTableTests.cs
Labels: area: async, type: feature

#2414 CreateTempTable cancellation token support and failure cleanup
  Source/LinqToDB/TempTable.cs
  Tests/Linq/Update/CreateTempTableTests.cs
Labels: area: async

#2423 SAP HANA native provider parameters fix
  Source/LinqToDB/Data/DataConnection.QueryRunner.cs
  Source/LinqToDB/DataProvider/Firebird/FirebirdSqlOptimizer.cs
  Source/LinqToDB/DataProvider/SapHana/SapHanaDataProvider.cs
  Source/LinqToDB/DataProvider/SapHana/SapHanaNativeSqlOptimizer.cs
  Source/LinqToDB/DataProvider/SapHana/SapHanaSqlBuilder.cs
  Source/LinqToDB/ServiceModel/RemoteDataContextBase.QueryRunner.cs
  Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs
  Source/LinqToDB/SqlProvider/ISqlOptimizer.cs
  Source/LinqToDB/SqlProvider/SqlOptimizerExtensions.cs
  Source/LinqToDB/SqlQuery/ConvertVisitor.cs
Labels: severity: critical
