Repository linq2db/linq2db, pull requests merged in 2024-06, with the labels that each got.

#2112 SQLite DateTime roundtrip improvements
  Tests/Linq/DataProvider/SQLiteTests.cs
Labels: area: mapping, provider: sqlite

#4477 WithOptions<T> loses CommandTimeout property
  Source/LinqToDB/DataOptions.cs
  Tests/Linq/Data/DataConnectionTests.cs
Labels: area: configuration

#4533 Fix non-lazy conditional evaluation
  Source/LinqToDB/DataProvider/ClickHouse/ClickHouseDataProvider.cs
  Source/LinqToDB/DataProvider/Informix/InformixSqlExpressionConvertVisitor.cs
  Source/LinqToDB/Linq/Builder/DefaultIfEmptyBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.Associations.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.EagerLoad.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.Expressions.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
  Source/LinqToDB/Linq/Builder/FirstSingleBuilder.cs
  Source/LinqToDB/Linq/Builder/ParametersContext.cs
  Source/LinqToDB/Linq/Builder/SelectManyBuilder.cs
  Source/LinqToDB/Linq/Builder/SequenceHelper.cs
  Source/LinqToDB/Linq/CompiledTableT.cs
  Source/LinqToDB/Linq/Query.cs
  Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs
  Source/LinqToDB/Linq/QueryRunner.cs
  Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
  Source/LinqToDB/SqlProvider/SqlExpressionConvertVisitor.cs
  Source/LinqToDB/SqlProvider/SqlExpressionOptimizerVisitor.cs
  Source/LinqToDB/SqlProvider/SqlProviderFlags.cs
  Source/LinqToDB/SqlQuery/SelectQueryOptimizerVisitor.cs
  Source/LinqToDB/SqlQuery/SqlInsertOrUpdateStatement.cs
  Source/LinqToDB/SqlQuery/Visitors/SqlQueryValidatorVisitor.cs
  Tests/Linq/Linq/ConditionalTests.cs
  Tests/Linq/Linq/GroupByTests.cs
  Tests/Linq/Linq/SubQueryTests.cs
  Tests/Linq/UserTests/Issue1700Tests.cs
Labels: type: bug, severity: regression
