Repository linq2db/linq2db, pull requests merged in 2024-01, with the labels that each got.

#4377 Fix nuget package vulnerability.
  Directory.Packages.props
  linq2db.sln.DotSettings
Labels: area: configuration

#4381 Add [Pure] to options.
  Source/LinqToDB/Common/OptionsContainer.cs
  Source/LinqToDB/DataOptions.cs
  Source/LinqToDB/Extensions/DataOptionsExtensions.Provider.cs
  Source/LinqToDB/Extensions/DataOptionsExtensions.cs
  Source/LinqToDB/Extensions/ReflectionExtensions.cs
  Source/LinqToDB/Extensions/ValueExtensions.cs
  Source/LinqToDB/LinqToDB.csproj
  linq2db.sln.DotSettings
Labels: status: ready for review

#4396 Bump version and year
  Build/Azure/pipelines/templates/build-vars.yml
  Build/BuildNuspecs.ps1
  Directory.Build.props
  MIT-LICENSE.txt
  Source/LinqToDB/Properties/LinqToDBConstants.cs
  Tests/Base/Properties/AssemblyInfo.cs
  Tests/Linq/Properties/AssemblyInfo.cs
Labels: status: ready for review

#4252 SqlOptions and IgnoreConstantExpressionInOrderBy option
  Build/Azure/pipelines/templates/build-job.yml
  Source/LinqToDB/Common/Configuration.cs
  Source/LinqToDB/Data/DataConnection.QueryRunner.cs
  Source/LinqToDB/DataOptions.cs
  Source/LinqToDB/DataProvider/ClickHouse/ClickHouseSqlBuilder.cs
  Source/LinqToDB/Extensions/DataOptionsExtensions.cs
  Source/LinqToDB/Linq/Builder/OrderByBuilder.cs
  Source/LinqToDB/Linq/Builder/SetOperationBuilder.cs
  Source/LinqToDB/Linq/IQueryContext.cs
  Source/LinqToDB/Linq/Query.cs
  Source/LinqToDB/Remote/LinqService.cs
  Source/LinqToDB/Remote/LinqServiceQuery.cs
  Source/LinqToDB/Remote/LinqServiceSerializer.cs
  Source/LinqToDB/Remote/RemoteDataContextBase.QueryRunner.cs
  Source/LinqToDB/SqlOptions.cs
  Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs
  Tests/Linq/Linq/OrderByTests.cs
  Tests/Model/Person.cs
Labels: area: sql, status: ready for review

#4393 Upgrade ClickHouse.Client package
  Directory.Packages.props
  Source/LinqToDB/DataProvider/ClickHouse/ClickHouseBulkCopy.cs
  Source/LinqToDB/DataProvider/ClickHouse/ClickHouseProviderAdapter.cs
  Tests/Linq/UserTests/Issue4389Tests.cs
Labels: status: ready for review, provider: clickhouse

#4376 Fix Sproc/Function/TableFunction sorting in T4
  Source/LinqToDB.Templates/LinqToDB.ttinclude
  Tests/Tests.T4/Databases/SqlServer.MS.generated.cs
  Tests/Tests.T4/Databases/SqlServer.MS.tt
  Tests/Tests.T4/Databases/SqlServer.generated.cs
  Tests/Tests.T4/Databases/SqlServer.tt
Labels: type: bug, area: T4, status: ready for review

#4386 Issue with generic class association member
  Source/LinqToDB/Linq/Builder/EagerLoading.cs
  Tests/Linq/UserTests/Issue4383Tests.cs
Labels: status: ready for review

#4378 Options small fixes and comments.
  Source/LinqToDB/Data/BulkCopyOptions.cs
  Source/LinqToDB/Data/ConnectionOptions.cs
  Source/LinqToDB/Data/QueryTraceOptions.cs
  Source/LinqToDB/Data/RetryPolicy/RetryPolicyOptions.cs
  Source/LinqToDB/DataContextOptions.cs
  Source/LinqToDB/DataProvider/Access/AccessOptions.cs
  Source/LinqToDB/DataProvider/ClickHouse/ClickHouseOptions.cs
  Source/LinqToDB/DataProvider/DB2/DB2Options.cs
  Source/LinqToDB/DataProvider/Firebird/FirebirdOptions.cs
  Source/LinqToDB/DataProvider/Informix/InformixOptions.cs
  Source/LinqToDB/DataProvider/MySql/MySqlOptions.cs
  Source/LinqToDB/DataProvider/Oracle/OracleOptions.cs
  Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLOptions.cs
  Source/LinqToDB/DataProvider/SQLite/SQLiteOptions.cs
  Source/LinqToDB/DataProvider/SapHana/SapHanaOptions.cs
  Source/LinqToDB/DataProvider/SqlCe/SqlCeOptions.cs
  Source/LinqToDB/DataProvider/SqlServer/SqlServerOptions.cs
  Source/LinqToDB/DataProvider/Sybase/SybaseOptions.cs
  Source/LinqToDB/LinqOptions.cs
Labels: status: ready for review

#4399 Concurrency issue in DataConnection options
  Source/LinqToDB/Common/OptionsContainer.cs
Labels: severity: critical, status: ready for review

#4397 Fix Oracle BulkCopy parameters
  Source/LinqToDB/DataProvider/Oracle/OracleBulkCopy.cs
  Tests/Linq/Update/BulkCopyTests.cs
Labels: status: ready for review

#4408 Assign new icon to nugets
  Build/BuildNuspecs.ps1
  NuGet/icon.png
  NuGet/icon300.png
  NuGet/icon64.png
  linq2db.sln
Labels: status: ready for review

#4406 Fix registration by `AddLinqToDBContext<TContext, TContextImplementation>`
  Source/LinqToDB.AspNet/ServiceConfigurationExtensions.cs
  Tests/Linq/Data/DataConnectionTests.cs
Labels: status: ready for review

#4339 Address Query Construction Bug
  Source/LinqToDB.Tools/Comparers/ComparerBuilder.cs
  Source/LinqToDB/Common/Internal/ValueComparer`.cs
  Source/LinqToDB/DataExtensions.cs
  Source/LinqToDB/Expressions/ExpressionConstants.cs
  Source/LinqToDB/Expressions/ExpressionEvaluator.cs
  Source/LinqToDB/Expressions/ExpressionInstances.cs
  Source/LinqToDB/Expressions/ExpressionVisitors/EqualsToVisitor.cs
  Source/LinqToDB/Expressions/TypeMapper/TypeMapper.cs
  Source/LinqToDB/Linq/Builder/AssociationHelper.cs
  Source/LinqToDB/Linq/Builder/EagerLoading.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.QueryBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs
  Source/LinqToDB/Linq/Builder/ExpressionTestGenerator.cs
  Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
  Source/LinqToDB/Linq/Builder/ParametersContext.cs
  Source/LinqToDB/Linq/Builder/SelectBuilder.cs
  Source/LinqToDB/Linq/Builder/SelectContext.cs
  Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs
  Source/LinqToDB/Linq/Builder/TableBuilder.cs
  Source/LinqToDB/Linq/TableT.cs
  Source/LinqToDB/LinqExtensions.Merge.cs
  Source/LinqToDB/LinqExtensions.cs
  Tests/Base/TestBase.cs
  Tests/Linq/DataProvider/SqlServerTypesTests.cs
  Tests/Linq/Linq/ConcatUnionTests.cs
  Tests/Linq/UserTests/Issue4337Tests.cs
Labels: type: bug, severity: regression, status: ready for review
