Repository linq2db/linq2db, pull requests merged in 2025-04, with the labels that each got.

#4911 Fix incorrect IsNullable defaults for Sql.FunctionAttribute
  Source/LinqToDB/Linq/Builder/ExpressionBuilder.Associations.cs
  Source/LinqToDB/Mapping/AssociationAttribute.cs
  Source/LinqToDB/Sql/IsNullableType.cs
  Source/LinqToDB/Sql/Sql.ExpressionAttribute.cs
  Source/LinqToDB/Sql/Sql.ExtensionAttribute.cs
  Source/LinqToDB/Sql/Sql.FunctionAttribute.cs
  Source/LinqToDB/Sql/Sql.PropertyAttribute.cs
  Source/LinqToDB/SqlQuery/QueryHelper.cs
  Source/LinqToDB/SqlQuery/SqlExpression.cs
  Source/LinqToDB/SqlQuery/SqlFunction.cs
  Source/LinqToDB/SqlQuery/SqlIsNullableType.cs
  Source/LinqToDB/SqlQuery/SqlRowExpression.cs
  Tests/Linq/Linq/FunctionTests.cs
Labels: severity: regression

#4916 Fix databases list for MergeWithOutput
  Source/LinqToDB/LinqExtensions.Merge.cs
Labels: area: documentation, status: ready for review

#4918 Add missing this to WithIgnoreEmptyUpdate and UseIgnoreEmptyUpdate extension methods
  Source/LinqToDB/Extensions/DataOptionsExtensions.cs
Labels: status: can be merged
